# 启动端口号
server:
  port: 8888
spring:
  elastic-job:
    reg-center:
      # elasticjob注册中心地址
      server-lists: localhost:2181
      # elasticjob注册命名空间
      namespace: elastic-job-lite-springboot
simple:
  job:
    demo:
      job:
        # 作业名称
        jobName: SimpleJobDemoTest
        # 任务执行的corn表达式
        cron: 0/5 * * * * ?
        # 任务分片总数
        shardingTotalCount: 1